bootstrap.servers=redpanda:9092
group.id=etl-research-connect

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false

offset.storage.topic=_connect_offsets
config.storage.topic=_connect_configs
status.storage.topic=_connect_status
offset.storage.replication.factor=1
config.storage.replication.factor=1
status.storage.replication.factor=1

rest.host.name=0.0.0.0
rest.port=8083
rest.advertised.host.name=kafka-connect
rest.advertised.port=8083

plugin.path=/opt/kafka/plugins
