workerId=standalone-worker-local
storePathRootDir=/tmp/rocketmq-connect-store

httpPort=8082

namesrvAddr=rocketmq-namesrv:9876

aclEnable=false
accessKey=rocketmq
secretKey=12345678

autoCreateGroupEnable=true
clusterName=DefaultCluster

pluginPaths=/workspace/local-setup/rocketmq-connect-src/distribution/target/rocketmq-connect-0.0.1-SNAPSHOT/rocketmq-connect-0.0.1-SNAPSHOT/lib/rocketmq-connect-sample-0.0.1-SNAPSHOT.jar
