env {
  job.mode = "STREAMING"
  execution.parallelism = 1
  checkpoint.interval = 10000
}

source {
  Kafka {
    bootstrap.servers = "redpanda:9092"
    topic = "wallet-events"
    consumer.group = "seatunnel-wallet-poc"
    format = "json"
    schema = {
      fields {
        event_id = "string"
        event_type = "string"
        wallet_id = "string"
        amount = "double"
        currency = "string"
      }
    }
  }
}

transform {
  Sql {
    plugin_input = "Kafka"
    plugin_output = "wallet_filtered"
    query = "select event_id, event_type, wallet_id, amount, currency, case when amount >= 1000 then 'HIGH' else 'STANDARD' end as risk_tier, 'seatunnel-wallet-poc' as pipeline from Kafka where event_type = 'wallet.payment.authorized' and amount >= 100"
  }
}

sink {
  Kafka {
    source_table_name = "wallet_filtered"
    bootstrap.servers = "redpanda:9092"
    topic = "wallet-filtered"
    format = "json"
  }
}
