spring.application.name=camel-wallet-pipeline
server.port=18084

camel.main.run-controller=true
camel.springboot.name=camel-wallet-pipeline

management.endpoints.web.exposure.include=health,info,camelroutes
management.endpoint.health.show-details=always

wallet.kafka.brokers=localhost:19092
wallet.kafka.group-id=camel-wallet-poc
